Add missing iconv module
Vimily/docker-laravel pull request #1
Opened 2021-08-05 05:48 UTC by prymag

[BJ-1886] Add missing iconv module

[Jira Ticket](https://bonjoro.atlassian.net/browse/BJ-1886)

#### Features

-   Item 1

#### Testing instructions

-   [ ] Step 1 ...

#### Analytics update required

-   [ ] Yes
-   [ ] No

#### List Updates

-   [ ] Change existing / new tracking etc...

#### Translation updates required?

-   [ ] Yes
-   [ ] No

#### GDPR updates required?

-   [ ] Yes
-   [ ] No

2021-08-09 21:28 UTC, deevus requested changes

2021-08-09 21:28 UTC, deevus commented on Dockerfile
> +RUN apk add gnu-libiconv=1.15-r3 --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.13/community/ --allow-untrusted
Did you test `gnu-libiconv` from the default repository?

2021-08-09 21:28 UTC, deevus commented on Dockerfile
> +RUN apk add gnu-libiconv=1.15-r3 --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.13/community/ --allow-untrusted
You didn't really explain in your commit why you had to do what you did here. If you come back in a years time you won't remember why you did it. 

Also, you need to syncronise this with the other Dockerfiles in php72 and php73 directories.

2021-08-09 22:01 UTC, deevus commented on Dockerfile
> +RUN apk add gnu-libiconv=1.15-r3 --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.13/community/ --allow-untrusted
I back-tracked our conversation on Slack. I think this is a much better implementation:

https://github.com/craftcms/docker/pull/35

2021-08-10 21:15 UTC, prymag commented on Dockerfile
> +RUN apk add gnu-libiconv=1.15-r3 --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.13/community/ --allow-untrusted
I updated my  commit. Please see 8d372c72df2ae05d0f11f8158655c5b804f39451.

I was not able to fully test the app on php72 - 73 as there were language features that aren't available on them. Though I tested the `iconv` function and it works.

2021-08-11 02:35 UTC, NeilDing666 approved these changes
LGTM!

2021-08-11 04:30 UTC, deevus approved these changes

2021-08-11 04:30 UTC, merged